// Flash-card UI: render one card at a time, flip hint/answer, filter by module,
// walk the deck in Ordered or Shuffle order, rate yourself, and pick up exactly
// where you left off. All card content comes from data/cards.json (generated by
// `cargo run --bin generate`); all per-user state lives in localStorage.

(() => {
  'use strict';

  const STORE_KEY = 'rust-flashcards:v1';

  const state = {
    cards: [],        // the deck, as loaded
    sequence: [],     // indices into `cards`, in the current walk order
    pos: 0,           // position within `sequence`
    mode: 'ordered',  // 'ordered' | 'shuffle'
    module: 'all',    // 'all' | a module dir
    attempts: {},     // cardId -> textarea contents
    ratings: {},      // cardId -> 'got' | 'review'
    shuffleOrder: null, // persisted shuffle as an array of card ids
  };

  const els = {
    host: document.getElementById('card-host'),
    progress: document.getElementById('progress'),
    prev: document.getElementById('prev'),
    next: document.getElementById('next'),
    ordered: document.getElementById('mode-ordered'),
    shuffle: document.getElementById('mode-shuffle'),
    module: document.getElementById('module-filter'),
  };

  // --- helpers ------------------------------------------------------------
  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[c]));
  }

  // Escape, then render markdown-style `inline code` as <code>.
  function richText(s) {
    return escapeHtml(s).replace(/`([^`]+)`/g, '<code class="inline">$1</code>');
  }

  function currentCard() {
    return state.cards[state.sequence[state.pos]];
  }

  function indexOfId(id) {
    return state.cards.findIndex((c) => c.id === id);
  }

  // Indices of cards in the active module, sorted by canonical order.
  function moduleIndices() {
    return state.cards
      .map((_, i) => i)
      .filter((i) => state.module === 'all' || state.cards[i].module === state.module)
      .sort((a, b) => state.cards[a].order - state.cards[b].order);
  }

  function shuffleInPlace(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }

  // Rebuild `sequence` for the current mode + module, keeping `preferId` if it
  // is still present. Reuses a persisted shuffle when it matches the card set.
  function buildSequence(preferId) {
    const base = moduleIndices();
    if (state.mode === 'shuffle') {
      const ids = base.map((i) => state.cards[i].id);
      const idSet = new Set(ids);
      const saved = state.shuffleOrder;
      const reusable = Array.isArray(saved)
        && saved.length === ids.length
        && saved.every((id) => idSet.has(id));
      const order = reusable ? saved : shuffleInPlace(ids.slice());
      state.shuffleOrder = order;
      state.sequence = order.map((id) => indexOfId(id));
    } else {
      state.sequence = base;
    }
    const at = preferId ? state.sequence.findIndex((i) => state.cards[i].id === preferId) : -1;
    state.pos = at >= 0 ? at : 0;
  }

  // --- persistence --------------------------------------------------------
  function save() {
    const card = currentCard();
    const data = {
      mode: state.mode,
      module: state.module,
      currentId: card ? card.id : null,
      attempts: state.attempts,
      ratings: state.ratings,
      shuffleOrder: state.mode === 'shuffle' ? state.shuffleOrder : null,
    };
    try {
      localStorage.setItem(STORE_KEY, JSON.stringify(data));
    } catch (_) { /* storage unavailable — run without persistence */ }
  }

  function load() {
    try {
      return JSON.parse(localStorage.getItem(STORE_KEY)) || {};
    } catch (_) {
      return {};
    }
  }

  // --- rendering ----------------------------------------------------------
  function cardHtml(card) {
    const quizBadge = card.is_quiz ? '<span class="badge badge-quiz">Quiz</span>' : '';
    const testsBadge = card.has_tests ? '<span class="badge badge-tests">Has tests</span>' : '';
    const concept = card.concept_summary
      ? `<p class="concept">${richText(card.concept_summary)}</p>`
      : '';

    const docs = (card.doc_links && card.doc_links.length)
      ? `<div class="doc-links"><span>Docs:</span> ${card.doc_links
          .map((u, i) => `<a href="${escapeHtml(u)}" target="_blank" rel="noopener">${i + 1}</a>`)
          .join('')}</div>`
      : '';

    const kindLabel = card.answer_kind === 'guidance' ? 'Guidance' : 'Solution';
    const answerBody = card.answer_kind === 'guidance'
      ? `<div class="guidance">${richText(card.answer)}</div>`
      : `<pre class="code"><code>${escapeHtml(card.answer)}</code></pre>`;

    const rating = state.ratings[card.id];
    const attempt = escapeHtml(state.attempts[card.id] || '');

    return `
      <article class="card">
        <div class="card-head">
          <span class="badge badge-module">${escapeHtml(card.module_title)}</span>
          ${quizBadge}${testsBadge}
          <span class="card-id">${escapeHtml(card.id)}</span>
        </div>
        ${concept}
        <div class="question">${richText(card.question)}</div>
        <details class="starter">
          <summary>Starter code</summary>
          <pre class="code"><code>${escapeHtml(card.exercise_code)}</code></pre>
        </details>
        <label class="attempt-label" for="attempt">Your answer</label>
        <textarea id="attempt" class="attempt" spellcheck="false"
          placeholder="Write your attempt here…">${attempt}</textarea>
        <div class="actions">
          <button id="hint-btn" class="action-btn" type="button">Show hint</button>
          <button id="answer-btn" class="action-btn action-primary" type="button">Show answer</button>
        </div>
        <section id="hint-panel" class="panel hint-panel" hidden>
          <h3 class="panel-title">Hint</h3>
          <div class="panel-body">${richText(card.hint)}</div>
        </section>
        <section id="answer-panel" class="panel answer-panel" hidden>
          <h3 class="panel-title">Answer
            <span class="answer-kind kind-${card.answer_kind}">${kindLabel}</span>
          </h3>
          ${answerBody}
        </section>
        <div class="rating">
          <span class="rating-q">Rate yourself:</span>
          <button id="rate-got" class="rate-btn rate-got ${rating === 'got' ? 'is-on' : ''}" type="button">✓ Got it</button>
          <button id="rate-review" class="rate-btn rate-review ${rating === 'review' ? 'is-on' : ''}" type="button">↻ Review</button>
        </div>
        ${docs}
      </article>`;
  }

  function wireCard(card) {
    document.getElementById('hint-btn').addEventListener('click', toggleHint);
    document.getElementById('answer-btn').addEventListener('click', toggleAnswer);
    document.getElementById('rate-got').addEventListener('click', () => rate('got'));
    document.getElementById('rate-review').addEventListener('click', () => rate('review'));

    const attempt = document.getElementById('attempt');
    attempt.addEventListener('input', () => {
      state.attempts[card.id] = attempt.value;
      save();
    });
  }

  function render() {
    const total = state.sequence.length;
    const card = currentCard();
    if (!card) {
      els.host.innerHTML = '<p class="loading">No cards in this module.</p>';
      els.progress.textContent = `0 / 0`;
      els.prev.disabled = true;
      els.next.disabled = true;
      return;
    }
    els.progress.textContent = `${state.pos + 1} / ${total}`;
    els.prev.disabled = state.pos === 0;
    els.next.disabled = state.pos === total - 1;
    els.host.innerHTML = cardHtml(card);
    wireCard(card);
  }

  // --- reveal panels (shared by clicks and keyboard) ----------------------
  function toggleHint() {
    const panel = document.getElementById('hint-panel');
    const btn = document.getElementById('hint-btn');
    if (!panel) return;
    panel.hidden = !panel.hidden;
    btn.textContent = panel.hidden ? 'Show hint' : 'Hide hint';
  }

  function toggleAnswer() {
    const panel = document.getElementById('answer-panel');
    const btn = document.getElementById('answer-btn');
    if (!panel) return;
    panel.hidden = !panel.hidden;
    btn.textContent = panel.hidden ? 'Show answer' : 'Hide answer';
  }

  // --- navigation / mode / module / rating --------------------------------
  function go(delta) {
    const total = state.sequence.length;
    state.pos = Math.min(Math.max(state.pos + delta, 0), total - 1);
    render();
    save();
  }

  function updateModeButtons() {
    for (const [btn, m] of [[els.ordered, 'ordered'], [els.shuffle, 'shuffle']]) {
      btn.classList.toggle('is-active', state.mode === m);
      btn.setAttribute('aria-pressed', String(state.mode === m));
    }
  }

  function setMode(mode) {
    if (mode === state.mode || !state.cards.length) return;
    const keepId = currentCard() ? currentCard().id : null;
    state.mode = mode;
    if (mode === 'shuffle') state.shuffleOrder = null; // explicit toggle reshuffles
    buildSequence(keepId);
    updateModeButtons();
    render();
    save();
  }

  function setModule(mod) {
    if (mod === state.module) return;
    state.module = mod;
    state.shuffleOrder = null; // card set changed; reshuffle if needed
    buildSequence(currentCard() ? currentCard().id : null);
    render();
    save();
  }

  function rate(value) {
    const card = currentCard();
    if (!card) return;
    if (state.ratings[card.id] === value) {
      delete state.ratings[card.id]; // clicking the active rating clears it
    } else {
      state.ratings[card.id] = value;
    }
    render();
    save();
  }

  // --- keyboard shortcuts -------------------------------------------------
  function onKey(e) {
    const tag = e.target && e.target.tagName;
    if (tag === 'TEXTAREA' || tag === 'INPUT' || tag === 'SELECT'
        || (e.target && e.target.isContentEditable)) {
      return; // don't hijack typing
    }
    const key = e.key;
    // Let a focused button handle its own Space activation (avoid double-fire).
    if ((key === ' ' || key === 'Spacebar') && tag === 'BUTTON') return;

    switch (key) {
      case 'ArrowRight': e.preventDefault(); go(1); break;
      case 'ArrowLeft': e.preventDefault(); go(-1); break;
      case ' ': case 'Spacebar': e.preventDefault(); toggleAnswer(); break;
      case 'h': case 'H': e.preventDefault(); toggleHint(); break;
      default: break;
    }
  }

  // --- module dropdown ----------------------------------------------------
  function populateModules() {
    const seen = new Set();
    const ordered = state.cards.slice().sort((a, b) => a.order - b.order);
    const options = [`<option value="all">All modules (${state.cards.length})</option>`];
    for (const c of ordered) {
      if (seen.has(c.module)) continue;
      seen.add(c.module);
      const count = state.cards.filter((x) => x.module === c.module).length;
      options.push(`<option value="${escapeHtml(c.module)}">${escapeHtml(c.module_title)} (${count})</option>`);
    }
    els.module.innerHTML = options.join('');
    els.module.value = state.module;
  }

  // --- init ---------------------------------------------------------------
  async function init() {
    const saved = load();
    try {
      const res = await fetch('data/cards.json');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const deck = await res.json();
      state.cards = deck.cards || [];
      if (!state.cards.length) throw new Error('the deck is empty');
    } catch (err) {
      els.host.innerHTML =
        `<p class="loading">Could not load the deck (${escapeHtml(err.message)}).<br>` +
        'Run <code class="inline">cargo run --bin generate</code> and reload.</p>';
      return;
    }

    // Restore saved preferences.
    state.attempts = (saved.attempts && typeof saved.attempts === 'object') ? saved.attempts : {};
    state.ratings = (saved.ratings && typeof saved.ratings === 'object') ? saved.ratings : {};
    const validModules = new Set(state.cards.map((c) => c.module));
    state.module = (saved.module === 'all' || validModules.has(saved.module)) ? saved.module : 'all';
    state.mode = saved.mode === 'shuffle' ? 'shuffle' : 'ordered';
    state.shuffleOrder = Array.isArray(saved.shuffleOrder) ? saved.shuffleOrder : null;

    populateModules();
    updateModeButtons();
    buildSequence(saved.currentId);
    render();
    save(); // normalize stored state (e.g. freshly generated shuffle order)

    els.prev.addEventListener('click', () => go(-1));
    els.next.addEventListener('click', () => go(1));
    els.ordered.addEventListener('click', () => setMode('ordered'));
    els.shuffle.addEventListener('click', () => setMode('shuffle'));
    els.module.addEventListener('change', () => setModule(els.module.value));
    document.addEventListener('keydown', onKey);
  }

  init();
})();
